server:
  port: 0

spring:
  application:
    name: CALIFICACION-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservicios

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
